In [1]:
import pandas as pd
import requests
import os
import json

In [2]:
raw_airport_data = pd.read_csv("raw_airline_delay_causes_2013_2018.csv")

In [3]:
raw_airport_data.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2014,4,AA,American Airlines Inc.,MFE,"Mission/McAllen/Edinburg, TX: McAllen Miller I...",146.0,34.0,15.17,0.59,...,0.0,12.50,0.0,0.0,2157.0,690.0,60.0,280.0,0.0,1127.0
1,2014,4,AA,American Airlines Inc.,ELP,"El Paso, TX: El Paso International",236.0,45.0,22.87,1.56,...,0.0,12.14,2.0,0.0,2221.0,1216.0,55.0,250.0,0.0,700.0
2,2014,4,AA,American Airlines Inc.,TPA,"Tampa, FL: Tampa International",476.0,93.0,37.16,6.16,...,0.0,24.99,0.0,0.0,4111.0,1392.0,611.0,860.0,0.0,1248.0
3,2014,4,AA,American Airlines Inc.,SAT,"San Antonio, TX: San Antonio International",438.0,106.0,44.75,4.79,...,0.0,32.08,2.0,2.0,5778.0,2378.0,400.0,1057.0,0.0,1943.0
4,2014,4,AA,American Airlines Inc.,MCI,"Kansas City, MO: Kansas City International",222.0,41.0,19.22,1.59,...,0.0,11.15,2.0,0.0,2012.0,880.0,271.0,299.0,0.0,562.0

In [4]:
#Rename columns: year, month and date
rename_airport_data = raw_airport_data.rename(columns={
    "Unnamed: 0": "uid",
    "year": "flight_year",
    " month": "flight_month",
    "airport": "locationID",
    })

In [5]:
rename_airport_data

,flight_year,flight_month,carrier,carrier_name,locationID,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2014,4,AA,American Airlines Inc.,MFE,"Mission/McAllen/Edinburg, TX: McAllen Miller I...",146.0,34.0,15.17,0.59,...,0.0,12.50,0.0,0.0,2157.0,690.0,60.0,280.0,0.0,1127.0
1,2014,4,AA,American Airlines Inc.,ELP,"El Paso, TX: El Paso International",236.0,45.0,22.87,1.56,...,0.0,12.14,2.0,0.0,2221.0,1216.0,55.0,250.0,0.0,700.0
2,2014,4,AA,American Airlines Inc.,TPA,"Tampa, FL: Tampa International",476.0,93.0,37.16,6.16,...,0.0,24.99,0.0,0.0,4111.0,1392.0,611.0,860.0,0.0,1248.0
3,2014,4,AA,American Airlines Inc.,SAT,"San Antonio, TX: San Antonio International",438.0,106.0,44.75,4.79,...,0.0,32.08,2.0,2.0,5778.0,2378.0,400.0,1057.0,0.0,1943.0
4,2014,4,AA,American Airlines Inc.,MCI,"Kansas City, MO: Kansas City International",222.0,41.0,19.22,1.59,...,0.0,11.15,2.0,0.0,2012.0,880.0,271.0,299.0,0.0,562.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88558,2018,12,YX,Republic Airline,TLH,"Tallahassee, FL: Tallahassee International",47.0,7.0,3.12,0.17,...,0.0,0.40,1.0,0.0,364.0,261.0,6.0,83.0,0.0,14.0
88559,2018,12,YX,Republic Airline,TUL,"Tulsa, OK: Tulsa International",39.0,5.0,0.63,0.00,...,0.0,1.38,0.0,0.0,228.0,24.0,0.0,100.0,0.0,104.0
88560,2018,12,YX,Republic Airline,TYS,"Knoxville, TN: McGhee Tyson",18.0,4.0,0.11,0.48,...,0.0,0.89,0.0,0.0,179.0,5.0,40.0,94.0,0.0,40.0
88561,2018,12,YX,Republic Airline,VPS,"Valparaiso, FL: Eglin AFB Destin Fort Walton B...",31.0,3.0,0.15,0.00,...,0.0,0.00,0.0,0.0,66.0,4.0,0.0,62.0,0.0,0.0
88562,2018,12,YX,Republic Airline,XNA,"Fayetteville, AR: Northwest Arkansas Regional",76.0,22.0,5.04,0.00,...,0.0,9.67,0.0,0.0,776.0,114.0,0.0,240.0,0.0,422.0

In [6]:
airport_data = rename_airport_data.filter([
        'flight_year',
        'flight_month',
        'carrier',
        'carrier_name',
        'locationID',
        'airport_name',
        'arr_flights',
        'arr_del15',
        'carrier_ct',
        'weather_ct',
        'security_ct',
        'late_aircraft_ct',
        'arr_cancelled',
        'arr_diverted',
        'arr_delay',
        'carrier_delay',
        'weather_delay',
        'nas_delay',
        'security_delay',
        'late_aircraft_delay',
    ])

In [7]:
airport_data.to_csv("clean_airport_delays_2013_2018.csv")